name: Commits Syntax Checker

on: [push]

jobs:
  check:
    name: Conventional Commits
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: webiny/action-conventional-commits@v1.3.0
