name: Commits Syntax Checker

on:
  push:
    branches: [actions]

jobs:
  check:
    name: Conventional Commits
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - uses: webiny/action-conventional-commits@v1.3.0
