name: Publish image in Docker Hub

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          TAG=${{ github.event.release.tag_name }}
          IMAGE=${{ secrets.DOCKER_USER }}/uvlhub

          docker build --build-arg VERSION_TAG=$TAG -t $IMAGE:$TAG -f docker/images/Dockerfile.prod .
          docker push $IMAGE:$TAG

          docker tag $IMAGE:$TAG $IMAGE:latest
          docker push $IMAGE:latest
