# ----------------------------------------------------------------------------
# Creative Commons CC BY 4.0 - David Romero - Diverso Lab
# ----------------------------------------------------------------------------
# This workflow is licensed under the Creative Commons Attribution 4.0
# International License. You are free to share and adapt the material
# as long as appropriate credit is given, a link to the license is provided,
# and you indicate if changes were made.
#
# For more details, visit:
# https://creativecommons.org/licenses/by/4.0/
# ----------------------------------------------------------------------------

name: Python Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 flake8-pyproject black isort

      - name: Lint with flake8
        run: flake8 app rosemary core

      - name: Check formatting with black
        run: black --check app rosemary core

      - name: Check import order with isort
        run: isort --check-only app rosemary core
