name: Run tests

on:
  push:
    branches: [actions2]

jobs:
  pytest:
    runs-on: ubuntu-22.04

    services:
      mariadb:
        image: mariadb:12.0.2
        env:
          MARIADB_ROOT_PASSWORD: uvlhub_root_password
          MARIADB_DATABASE: uvlhubdb_test
          MARIADB_USER: uvlhub_user
          MARIADB_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mariadb-admin ping -u root -p$MARIADB_ROOT_PASSWORD"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Delete rosemary editable mode
        run: sed -i '/rosemary @ file:\/\/\/app/d' requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          FLASK_ENV: testing
          MARIADB_HOSTNAME: 127.0.0.1
          MARIADB_PORT: 3306
          MARIADB_ROOT_PASSWORD: uvlhub_root_password
          MARIADB_TEST_DATABASE: uvlhubdb_test
          MARIADB_USER: uvlhub_user
          MARIADB_PASSWORD: uvlhub_password
        run: pytest app/modules/ --ignore-glob='*selenium*'
